### ISSUE TITLE
百度URL验证错误

### ISSUE THREAD

**Issue by X-CCS** [xuyungit/xtts#1]
你好！在运行你的程序的时候。命名行是这样的
`Python3.6 --book ./readbook.txt --id '15414045' --secret'g79fxW3Zqw1qrYKeQHmufv8zNXafc6Vt'`

但是出现了错误
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>`
我觉得应该是baidu_oauth_url的错误，请问下你这里有什么改进的建议吗？能否交流下

**Comment by xuyungit** [comment]
首先是您这个id似乎不对，在浏览器里访问
`https://openapi.baidu.com/oauth/2.0/token?grant_type=client_credentials&client_id=15414045&client_secret=g79fxW3Zqw1qrYKeQHmufv8zNXafc6Vt&`
也不能成功获取token
这个id是百度云管理中心的应用列表里的API Key。
